# apiVersion: extensions/v1beta1  # If you are in Kubernetes version 1.8 or less please use this line instead of the following one
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-image-analyzer
  labels:
    app: sysdig-image-analyzer
spec:
  selector:
    matchLabels:
      app: sysdig-image-analyzer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sysdig-image-analyzer
    spec:
      volumes:
      # Needed for cri-o image inspection
      - name: etccontainers-vol
        hostPath:
          path: /etc/containers
      # Needed for cri-o image inspection
      - name: varlibcontainers-vol
        hostPath:
          path: /var/lib/containers
      # Needed for socket access
      - name: varrun-vol
        hostPath:
          path: /var/run
      - name: sysdig-image-analyzer-config
        configMap:
          name: sysdig-image-analyzer
          optional: true
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      # The following line is necessary for RBAC
      serviceAccount: sysdig-agent
      terminationGracePeriodSeconds: 5
      imagePullSecrets:
      - name: artifactory
      containers:
      - name: sysdig-image-analyzer
        # TODO change image repo with Docker Hub 
        image: docker.internal.sysdig.com/image-analyzer:dev
        securityContext:
          # needed for the CRI socket
          privileged: true
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 1024Mi
        env:
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sysdig-agent
              key: access-key
        - name: IA_IMAGE_PERIOD
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: image_period
              optional: true
        - name: IA_IMAGE_CACHE_TTL
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: image_cache_ttl
              optional: true
        - name: IA_REPORT_PERIOD
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: report_period
              optional: true
        - name: DOCKER_SOCKET_PATH
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: docker_socket_path
              optional: true
        - name: CRI_SOCKET_PATH
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: cri_socket_path
              optional: true
        - name: AM_COLLECTOR_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: collector_endpoint
              optional: true
        - name: AM_COLLECTOR_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: collector_timeout
              optional: true
        - name: CHECK_CERTIFICATE
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: check_certificate
              optional: true
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: sysdig-image-analyzer
              key: debug
              optional: true
        volumeMounts:
        - mountPath: /var/run
          name: varrun-vol
        - mountPath: /etc/containers
          name: etccontainers-vol
          readOnly: true
        - mountPath: /var/lib/containers
          name: varlibcontainers-vol
