apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
data:
  dragent.yaml: |
    configmap: true
    ### Agent tags
    # tags: linux:ubuntu,dept:dev,local:nyc

    #### Sysdig Software related config ####

    # Sysdig collector address
    # collector: 192.168.1.1

    # Collector TCP port
    # collector_port: 6666

    # Whether collector accepts ssl
    # ssl: true

    # collector certificate validation
    # ssl_verify_certificate: true

    #######################################
    # new_k8s: true
    # k8s_cluster_name: production
    security:
      k8s_audit_server_url: 0.0.0.0
      k8s_audit_server_port: 7765
  prometheus.yaml: |
    global:
      scrape_interval: 10s

    #scrape_configs:
    #- job_name: 'default'
    #  sample_limit: 2000
    #  sysdig_sd_configs: # default relabeling config
    #  relabel_configs:
    #  metric_relabel_configs:
    #- job_name: 'app'
    #  sysdig_sd_configs:
    #  - tags:
    #      namespace: default
    #      deployment: app
    #  relabel_configs:
    #  metric_relabel_configs:
