apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-image-analyzer
data:
  debug: "true"
  collector_endpoint: "https://collector-staging3.sysdigcloud.com/internal/scanning/scanning-analysis-collector"